### ISSUE TITLE
disabling bibliographies module produces errors

### ISSUE THREAD

**Issue by lyokha** [vim-pandoc/vim-pandoc#118]
I made following settings in my ``.vimrc``

```vim
let g:pandoc#modules#disabled = ['menu', 'spell', 'bibliographies']
```

This made producing pdf output always complain

```
Обнаружена ошибка при обработке function pandoc#command#Pandoc:
строка    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lyokha/.vim/pythonx/vim_pandoc/command.py", line 121, in __call__
    buffer_bibliographies = vim.eval('b:pandoc_biblio_bibs')
vim.error: Vim:E121: Неопределённая переменная: b:pandoc_biblio_bibs
```

There is some Russian above but the idea is clear: variable ``b:pandoc_biblio_bibs`` has not been defined. Changing

```python
        buffer_bibliographies = vim.eval('b:pandoc_biblio_bibs')
        if len(buffer_bibliographies) < 1:
            buffer_bibliographies = find_bibfiles()
        bib_arg = " ".join(['--bibliography "' + i  + '"' for i in buffer_bibliographies]) if \
                len(buffer_bibliographies) > 0 \
                else ""
```

to

```python
        bib_arg = ""
        if vim.eval('index(g:pandoc#modules#disabled, "bibliographies")') == -1:
            buffer_bibliographies = vim.eval('b:pandoc_biblio_bibs')
            if len(buffer_bibliographies) < 1:
                buffer_bibliographies = find_bibfiles()
            bib_arg = " ".join(['--bibliography "' + i  + '"' for i in buffer_bibliographies]) if \
                    len(buffer_bibliographies) > 0 \
                    else ""
```

in command.py PandocCommand() fixed the issue for me but i am not sure if it is a good solution.

Another small issue (a typo) i found in the doc/pandoc.txt: there is line

```
module will gather bibliographies on the following orderi (between brackets,
```

Small fix: ``s/orderi/order/``

**Comment by fmoralesc** [comment]
Should be fixed now, please confirm.

**Comment by lyokha** [comment]
New error due to missing colon after else on line 131:

```
Обнаружена ошибка при обработке function pandoc#command#Pandoc:
строка    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lyokha/.vim/pythonx/vim_pandoc/command.py", line 131
    else
       ^
SyntaxError: invalid syntax
строка    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
```

When i added the semicolon all began to work fine. Thanks!

**Comment by fmoralesc** [comment]
I've been writing way too much viml lately it seems! Fixed now.
