### ISSUE TITLE
Terminal vim throwing error

### ISSUE THREAD

**Issue by mclearc** [vim-pandoc/vim-pandoc#121]
I've tried to remove all need for MacVim with the following applescript, which calls terminal vim when I click on (or otherwise open) a file via OS X's Finder.

>on run {input, parameters}
	set cmd to "/usr/local/bin/vim -c startinsert"
	if input is not in {} then
		set myPath to POSIX path of input
		set cmd to "/usr/local/bin/vim " & quote & myPath & quote
	end if
>	
>	tell application "iTerm"
		activate
		set myTerm to (current terminal)
		tell myTerm
			set mySession to (make new session at the end of sessions)
			tell mySession to exec command cmd
		end tell
	end tell
end run

However, when I try to use vim-pandoc from such an opened buffer, it throws errors (vim-pandoc works fine in other terminal sessions where the files are not opened using the applescript above).

>Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Roambot/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line 350, in <module>
    pandoc = PandocCommand()
  File "/Users/Roambot/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line 176, in __init__
    self.opts = PandocHelpParser()
  File "/Users/Roambot/.vim/plugged/vim-pandoc/pythonx/vim_pandoc/command.py", line 67, in __init__
    self._help_data = Popen(["pandoc", "--help"], stdout=PIPE).communicate()[0]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined

My suspicion is that the problem lies in the fact that the script calls vim via the `exec` command. But I'm not sure why this would throw any errors.

**Comment by fmoralesc** [comment]
This sounds like it doesn't find `pandoc` in `$PATH`. Can you add it explicitely in your script?

**Comment by mclearc** [comment]
Turns out it is a [known bug](http://apple.stackexchange.com/questions/153402/in-osx-yosemite-why-can-i-set-many-environment-variables-for-gui-apps-but-cann?rq=1) with Yosemite's handling of environment variables. I've figured out a workaround. thanks,
