### ISSUE TITLE
Neovim throws AttributeError when trying to ouptut pdf

### ISSUE THREAD

**Issue by edVonSchleck** [vim-pandoc/vim-pandoc#160]
Hi,

I'm having a problem when trying to output to pdf
(writing to html works):

`Error detected while processing function pandoc#command#AutoPandoc[9]..pandoc#command#Pandoc[5]..provider#python3#Call:                                                                         
line   18:                                                                                                                                                                                      
AttributeError("'str' object has no attribute 'decode'",)                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                              
  File "/usr/local/lib/python3.4/dist-packages/neovim/msgpack_rpc/session.py", line 181, in handler                                                                                             
    rv = self._request_cb(name, args)                                                                                                                                                           
  File "/usr/local/lib/python3.4/dist-packages/neovim/api/common.py", line 237, in filter_request_cb                                                                                            
    walk(self._in, args, self, name, 'request'))                                                                                                                                                
  File "/usr/local/lib/python3.4/dist-packages/neovim/plugin/host.py", line 69, in _on_request                                                                                                  
    rv = handler(*args)                                                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/neovim/plugin/host.py", line 166, in <lambda>                                                                                                    
    decoder = lambda fn, hook, *args: fn(*hook.walk(args))                                                                                                                                      
  File "/usr/local/lib/python3.4/dist-packages/neovim/plugin/script_host.py", line 77, in python_execute                                                                                        
    exec(script, self.module.__dict__)                                                                                                                                                          
AttributeError: 'str' object has no attribute 'decode' `

Running :Pandoc manually works (outputting to html).
Running :Pandoc pdf (either manually or after write) fails.
I tried both latex engines: xelatex and pdflatex, both did not work.
Running pandoc from the command line in bash works as expected

Any suggestions?
Thanks
Ed

**Comment by fmoralesc** [comment]
I just pushed a change to master that I think fixes this. Please test.

**Comment by edVonSchleck** [comment]
Hi,
your change fixed this issue.

Thanks for the quick reply.
Ed
