### ISSUE TITLE
"No module named glob"

### ISSUE THREAD

**Issue by thenerdlawyer** [vim-pandoc/vim-pandoc#165]
a few weeks ago, I started getting the following error message whenever I open a new buffer:

    Error detected while processing function pandoc#bibliographies#Init:
    line   39:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/NerdLawyer/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/bib/vim_completer.py", line 4, in <module>
        from vim_pandoc.bib.collator import SourceCollator
      File "/Users/NerdLawyer/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/bib/collator.py", line 2, in <module>
        from glob import glob
    ImportError: No module named glob

I *think* this started happening after I upgraded MacVim, and I don't get the error using regular Vim in iTerm.

**Comment by fmoralesc** [comment]
This is weird, `glob` is part of the python standard library, so I suspect this has something to do with your macvim build.

**Comment by thenerdlawyer** [comment]
I uninstalled and reinstalled python, pandoc, and mvim; that solved the problem.
