### ISSUE TITLE
Pandoc pdf process error on 10.11.6

### ISSUE THREAD

**Issue by maccius** [vim-pandoc/vim-pandoc#193]
In the last week or so, I have started to receive the following error when trying to convert a pandoc-md document to PDF using vim-pandoc:
~~~
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Gordie/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 78, in <module>
    class PandocHelpParser(object):
  File "/Users/Gordie/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 110, in PandocHelpParser
    @wrap_formats
  File "/Users/Gordie/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 75, in wrap_formats
    data = fn()
  File "/Users/Gordie/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 112, in _get_input_formats
    return get_raw_pandoc_data("Input formats:(.*)Output formats")
  File "/Users/Gordie/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 67, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
~~~

A similar issue was filed and then closed last year: https://github.com/vim-pandoc/vim-pandoc/issues/133

Though that was eventually closed, someone commented a few days ago that they are having the same issue as I am.  Moreover, the fix recommended in that thread is no longer working.  

I have recreated this in MacVim (v.8 114), console vim (v.8 55), and NeoVim (0.20-dev, compiled via Homebrew).  I've also tried reinstalling python, changing around various environment settings, and confirming that command-line `pandoc` works properly (it does).

Any help you could provide will be much appreciated.

**Comment by fmoralesc** [comment]
The output of `pandoc --help`, on which we relied on to get the suported formats changed. I need to adjust the code so it uses the output of `--list-input-formats`/`--list-output-formats` instead.

**Comment by maccius** [comment]
Ah, I see!  Thanks for explaining.  I wasn’t sure whether the problem originated with `pandoc` itself, or with something in my Python + Vim setup.

**Comment by maccius** [comment]
Awesome!  I just updated and it works perfectly.  Thank you for the quick fix!  I really appreciate it.
