### ISSUE TITLE
Buffer-local latex engine

### ISSUE THREAD

**Issue by JeffreyFalgout** [vim-pandoc/vim-pandoc#202]
I've run into a situation where I'd like to use the default latex engine (xelatex) as my latex engine for most of my pandoc files, but there are some features that I would like to use that xelatex does not support. For these files, I would like to switch the latex engine to pdflatex.

Currently, I'm adding `latex-engine: pdflatex` to the YAML metadata block and parsing that from vimscript. I use the parsed latex engine in the autoexec command with `exec 'Pandoc pdf --latex-engine=' b:pandoc_command_latex_engine`.

Is this something you would be interested in officially supporting?

**Comment by fmoralesc** [comment]
I allow a buffer-local latex engine now. I only need to have code that parses the yaml header and set the variable, the Pandoc command should pick it up by itself.

**Comment by JeffreyFalgout** [comment]
I've been using [this function](https://github.com/JeffreyFalgout/dotfiles/blob/master/.vim/autoload/pandoc/engine.vim) to parse the metadata block:

```vim
function! pandoc#engine#GetLatexEngine()
    let l:num_lines = line('$')
    if l:num_lines >= 1
        let l:line = getline(1)
        " If there's a metadata block, scan it.
        if l:line == '---'
            let l:line_num = 2
            let l:line = getline(l:line_num)

            " Scan until the metadata block closes or the end of the file.
            while l:line != '---' && l:line_num <= l:num_lines
                if l:line =~ '^latex-engine: \w\+'
                    return split(l:line)[1]
                end

                let l:line_num = l:line_num + 1
                let l:line = getline(l:line_num)
            endwhile
        endif
    end

    " Return the default latex engine if one isn't found.
    return g:pandoc#command#latex_engine
endfunction
```

**Comment by fmoralesc** [comment]
Thanks. I just added a new module that parses yaml headers, I only have to plug it to the command module.

**Comment by fmoralesc** [comment]
Should be working as of https://github.com/vim-pandoc/vim-pandoc/commit/8005a1f74b350576d1ec44d1ec15fceba58f1208. Can you confirm?

**Comment by JeffreyFalgout** [comment]
```
Error detected while processing function pandoc#command#Init:
line   13:
E121: Undefined variable: latex_engine
E15: Invalid expression: b:pandoc_yaml_data[latex_engine]
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 229, in __call__
    and self.opts.in_allowed_formats(c_args[0]) \
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 185, in in_allowed_formats
    if not identifier.startswith("markdown") and identifier in PandocHelpParser.get_output_formats_table():
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 134, in get_output_formats_table
    for i in PandocHelpParser._get_output_formats():
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 129, in _get_output_formats
    return wrap_formats(get_raw_pandoc_data("Output formats:(.*)\[\*+for pdf"))
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 74, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

Should `latex-engine` be put in quotes?

**Comment by fmoralesc** [comment]
Pretty much. My bad for "flying blind" 😜

**Comment by fmoralesc** [comment]
It should be OK now, I think.

**Comment by JeffreyFalgout** [comment]
Getting a new error now:

```
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 229, in __call__
    and self.opts.in_allowed_formats(c_args[0]) \
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 185, in in_allowed_formats
    if not identifier.startswith("markdown") and identifier in PandocHelpParser.get_output_formats_table():
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 134, in get_output_formats_table
    for i in PandocHelpParser._get_output_formats():
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 129, in _get_output_formats
    return wrap_formats(get_raw_pandoc_data("Output formats:(.*)\[\*+for pdf"))
  File "/home/jeffrey/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 74, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by fmoralesc** [comment]
Can't reproduce. What vim's and pandoc's version are you using? Are you using python2 or python3 support?

**Comment by JeffreyFalgout** [comment]
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm  
```
```
$ python --version
Python 2.7.12
```

```
$ python3 --version
Python 3.5.2
```

**Comment by fmoralesc** [comment]
Hm... I can't reproduce on vim 8 with python 3+, at least with this test file:

```
---
title: This is a test
author: Hello!
latex-engine: pdflatex
...

test test
```

What is `pandoc`'s version? I am using 1.19.1.

**Comment by JeffreyFalgout** [comment]
My pandoc version is 1.17.2.

[This commit](https://github.com/vim-pandoc/vim-pandoc/commit/9c894549da14aa6109020f8555705da220ba5a69) fixed the issue.

**Comment by fmoralesc** [comment]
Great to hear!
