### ISSUE TITLE
Pandoc command.py  fails in windows

### ISSUE THREAD

**Issue by Wixophe** [vim-pandoc/vim-pandoc#242]
Thanks for the great work!
It seems that the refactoring (pandocinfo) is creating issues for me:

Using pandoc 2.0.2, latest pandoc scripts, python 3.5, vim 8.0.
Create a new .md file, call :Pandoc! HTML, get the following error:

Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\PortablePrograms\Vim/vimfiles\pythonx\vim_pandoc\command.py", line 240, in <module>
    pandoc = PandocCommand()
  File "C:\PortablePrograms\Vim/vimfiles\pythonx\vim_pandoc\command.py", line 17, in __init__
    self.pandoc_info = PandocInfo(vim.vars["pandoc#command#path"])
  File "C:\PortablePrograms\Vim/vimfiles\pythonx\vim_pandoc\helpparser.py", line 12, in __init__
    self.update()
  File "C:\PortablePrograms\Vim/vimfiles\pythonx\vim_pandoc\helpparser.py", line 22, in update
    self.version = self.get_version()
  File "C:\PortablePrograms\Vim/vimfiles\pythonx\vim_pandoc\helpparser.py", line 29, in get_version
    return self.__raw_output('--version', pattern=b'pandoc (\d+\.\d+)').decode()
  File "C:\PortablePrograms\Vim/vimfiles\pythonx\vim_pandoc\helpparser.py", line 15, in __raw_output
    data = Popen([self.pandoc, cmd], stdout=PIPE).communicate()[0]
  File "C:\Python35_32\Lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Python35_32\Lib\subprocess.py", line 929, in _execute_child
    args = list2cmdline(args)
  File "C:\Python35_32\Lib\subprocess.py", line 441, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined

**Comment by fmoralesc** [comment]
I will move the codebase to be python3 only, so I can check this more readily.

**Comment by Wixophe** [comment]
Thanks. In the meantime, I reverted back to 59e060fd7ffe43adcab9e6fb575afa5660d6ad91 (I did not try many other versions). I had to locally change from --latex-engine to --pdf-engine in command.py for this older version to work with the latex Pandoc.

**Comment by fmoralesc** [comment]
I already have some work done for this in the py3-refactor branch. The issue is that vim and neovim's implementations of the python interface is that the datatypes are not always compatible, and since I use neovim sometimes I don't catch these mistakes in due time.

**Comment by Wixophe** [comment]
Thanks, but...Not sure if should open another issue or not, but now I get this error:
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\PortablePrograms\Vim/vimfiles\python3\vim_pandoc\command.py", line 136, in __call__
    self._run_command = " ".join(arglist)
TypeError: sequence item 0: expected str instance, bytes found

**Comment by fmoralesc** [comment]
Yeah, it's basically the same issue. You are using a custom pandoc command, right? The problem is that vim gets a bytes object when accessing the variable, and neovim (which I use) gets a string. So there is a lot of points where the mismatch causes these errors. I'm really sorry for the inconvenience, but the whole process is uncovering what parts of the codebase are sensitive to the underlying problem.

**Comment by Wixophe** [comment]
What do you mean by "custom pandoc command"? At some point, I did have a "let g:pandoc#command#path=...", but I commented it out. Oh well, I will go back to that revision that works for me for now - this script is really handy, I don't want to just remove it!
Thanks.

**Comment by fmoralesc** [comment]
I thought the error was caused by either that variable being passed as a bytestring, because of the point where the previous error arises (the `Popen()` call, which would take the path as its first command).

Don't worry, this should be sorted out shortly ;) I just wish upstream vim and neovim's `vim` python module hadn't diverged!

**Comment by Gankarloo** [comment]
Any news on this?

Installed vim-pandoc today and get a lot of python stack traces.

**Environment:**
Windows 10
gvim 8.2 patch 1139

**command: Pandoc HTML**
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\command.py", line 284, in <module>
    pandoc = PandocCommand()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\command.py", line 17, in __init__
    self.pandoc_info = PandocInfo(vim.vars["pandoc#command#path"])
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 16, in __init__
    self.update()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 26, in update
    self.version = self.get_version()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 38, in get_version
    return self.__raw_output('--version', pattern=versionPattern)
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 21, in __raw_output
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Command: Pandoc <TAB>**
Error detected while processing function pandoc#command#PandocComplete:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 16, in __init__
    self.update()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 26, in update
    self.version = self.get_version()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 38, in get_version
    return self.__raw_output('--version', pattern=versionPattern)
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 21, in __raw_output
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Command: Pandoc**
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\command.py", line 284, in <module>
    pandoc = PandocCommand()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\command.py", line 17, in __init__
    self.pandoc_info = PandocInfo(vim.vars["pandoc#command#path"])
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 16, in __init__
    self.update()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 26, in update
    self.version = self.get_version()
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 38, in get_version
    return self.__raw_output('--version', pattern=versionPattern)
  File "C:\Users\ankarloog\vimfiles\pack\minpac\start\vim-pandoc\python3\vim_pandoc\helpparser.py", line 21, in __raw_output
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'


Is there anything more I can provide?
