### ISSUE TITLE
command module error: conflicting option string -o

### ISSUE THREAD

**Issue by MageJohn** [vim-pandoc/vim-pandoc#253]
I'm getting an error when trying to use any :Pandoc command. I get the same error regardless of the arguments I pass, or even if I pass arguments at all. 

```
Error detected while processing function pandoc#command#Pandoc[5]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/magejohn/.config/nvim/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 51, in __call__
    p = self.pandoc_info.build_argument_parser()
  File "/home/magejohn/.config/nvim/plugged/vim-pandoc/python3/vim_pandoc/helpparser.py", line 118, in build_argument_parser
    parser.add_argument(*flags, **extra)
  File "/usr/lib/python3.5/argparse.py", line 1353, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1716, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1557, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.5/argparse.py", line 1367, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.5/argparse.py", line 1506, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.5/argparse.py", line 1515, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -o/--output: conflicting option string: -o
```

I'm using NVIM v0.2.3-dev, and :checkhealth shows that python3 support is fully working. vim-pandoc up to date, too. Any idea what could be causing it?

**Comment by fmoralesc** [comment]
What is your pandoc version?

**Comment by MageJohn** [comment]
Ah, I knew I must have missed something. :) 

pandoc 1.16.0.2

**Comment by fmoralesc** [comment]
At least I hinted at the solution - I did nothing really ;)
