### ISSUE TITLE
Spaces in bibliography and vim echo error

### ISSUE THREAD

**Issue by javiertury** [vim-pandoc/vim-pandoc#262]
Trying to execute `:Pandoc pdf` returns this error

```
Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "/hidden-path/.vim/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 175, in execute
    com = Popen(shlex.split(self._run_command), stdout=tmp, stderr=tmp)
  File "/usr/lib64/python3.6/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib64/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.6/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/hidden-path/.vim/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 141, in __call__
    self.execute(should_open)
  File "/hidden-path/.vim/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 178, in execute
    vim.command('echoe "vim-pandoc: could not execute pandoc"')
vim.error: Vim(echoerr):vim-pandoc: could not execute pandoc
```

So there are two errors. The first one is that the string `self._run_command` cannot be processed by `shlex.split()`. Displaying the error message in vim triggers another error because of this line

```
vim.command('echoe "vim-pandoc: could not execute pandoc"')
```

Going back to the first error, inspecting the variable `self._run_command` yields

```
pandoc  --to="latex" --output="idea.pdf" --latex-engine="xelatex" --bibliography=""Advanced" --bibliography="/hidden-path-on-purpose/Advanced Research Topics.bib" "idea.md"
```
So the problem is with the bilbiography yaml header which contains spaces and is surrounded by quotes. The first bibliography field begins with double double-quotes, the second field looks alright.

```
---
bibliography: "Advance Research Topics.bib"
---
```

**Comment by fmoralesc** [comment]
This was two issues: the YAML value extraction procedure was faulty. It should be fixed now in master. I also added a check so YAML bibliographies are added only if the paths are readable.
