### ISSUE TITLE
:Pandoc command fails (only after running once)

### ISSUE THREAD

**Issue by PunkPhysicist** [vim-pandoc/vim-pandoc#307]
The first time I run the `Pandoc` command to compile a markdown to pdf, everything works fine. Any subsequent try to call the command yields the following error:
```
Error detected while processing function pandoc#command#Pandoc[5]..provider#python3#Call:                                                                                            
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/******/.vim/bundle/vim-pandoc/python3/vim_pandoc/command.py", line 141, in __call__
    self.execute(should_open)
  File "/home/******/.vim/bundle/vim-pandoc/python3/vim_pandoc/command.py", line 155, in execute
    vim.command(wnr + "wincmd c")
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(close):E444: Cannot close last window'
Error detected while processing function pandoc#command#Pandoc:
line    5:
E171: Missing :endif
```

The cause seems to be different then other similar issues, at least given the error message (e.g. https://github.com/vim-pandoc/vim-pandoc/issues/255 or https://github.com/vim-pandoc/vim-pandoc/issues/298).

Current setup:
neovim 0.3.5-1 (with python 3 plugin)
Python 3.7.3

**Comment by fmoralesc** [comment]
Does the problem go away if you add

```
                vim.command("setlocal buftype=nofile")
                vim.command("setlocal bufhidden=wipe")
```
after line 157 in `python3/vim_pandoc/command.py`? (that is, after `botright 5new pandoc-execute`).

**Comment by PunkPhysicist** [comment]
This seemed to fix the problem for me.

Thanks
