### ISSUE TITLE
Pandoc command fails on MSYS

### ISSUE THREAD

**Issue by 1earch** [vim-pandoc/vim-pandoc#320]
I tried to use vim-pandoc on an MSYS (mingw64) terminal, with Python3 installed, but the following error is produced:

```
Error detected while processing function pandoc#command#Pandoc:
ligne    2 :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/c/Users/xx/Documents/Cmder/vimfiles/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 283, in <module>
    pandoc = PandocCommand()
  File "/c/Users/xx/Documents/Cmder/vimfiles/plugged/vim-pandoc/python3/vim_pandoc/command.py", line 17, in __init__
    self.pandoc_info = PandocInfo(vim.vars["pandoc#command#path"])
  File "/c/Users/xx/Documents/Cmder/vimfiles/plugged/vim-pandoc/python3/vim_pandoc/helpparser.py", line 15, in __init__
    self.update()
  File "/c/Users/xx/Documents/Cmder/vimfiles/plugged/vim-pandoc/python3/vim_pandoc/helpparser.py", line 25, in update
    self.version = self.get_version()
  File "/c/Users/xx/Documents/Cmder/vimfiles/plugged/vim-pandoc/python3/vim_pandoc/helpparser.py", line 32, in get_version
    return self.__raw_output('--version', pattern='pandoc (\d+\.\d+)')
  File "/c/Users/xx/Documents/Cmder/vimfiles/plugged/vim-pandoc/python3/vim_pandoc/helpparser.py", line 20, in __raw_output
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ligne    7 :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
```

**Steps to reproduce:**
1. Follow the [Git4windows install guide for MSYS2](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper)
2. Install python in the MSYS environment (`pacboy sync msys/python`)
3. Check that Python is installed, in `vim`, executing `:py3 print("hello")`
4. Download pandoc and add the executable to `%PATH%` (Windows environment variable)
5. Load `vim-pandoc` thanks to Plug
6. Create a new `.md` file and try building it with `:Pandoc`

**Comment by 1earch** [comment]
Note: this issue may be related to #242

**Comment by fmoralesc** [comment]
Thanks for the fix, @1earch! If things are right now, can you close the issue ;)

**Comment by 1earch** [comment]
Thanks for your quick merge 🙂

**Comment by fmoralesc** [comment]
It was a good way to distract me from the heat wave we are having here ;)
