### ISSUE TITLE
:Pandoc fails with AttributeError

### ISSUE THREAD

**Issue by vvizzo** [vim-pandoc/vim-pandoc#327]
Related to #224 

Trying to do :Pandoc html

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 238, in __call__
    and self.opts.in_allowed_formats(c_args[0]) \
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 188, in in_allowed_formats
    if not identifier.startswith("markdown") and identifier in PandocHelpParser.get_output_formats_table():
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 137, in get_output_formats_table
    for i in PandocHelpParser._get_output_formats():
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 132, in _get_output_formats
    return wrap_formats(get_raw_pandoc_data("Output formats:(.*)\[\*+for pdf"))
  File "/home/Mikolaj/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 77, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```
with newest pandoc:

```
pandoc.exe 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: C:\Users\Mikolaj\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

and newest vim-pandoc. Line mentioned in #224  is with >=

TIA

v.

**Comment by sticke4** [comment]
I had this issue as well. I'm running on Windows 10, with the newest version of pandoc installed through chocolatey. I fixed it doing two steps. 

1. Remove the vim-pandoc folder and reclone the repo. I use vim-plug so I deleted the folder in my plugins folder and ran `PlugInstall`. 

The python stack trace in your posted error refers to the folder `pythonx` which doesn't exist in the current version of the repo. The current version only has the `python3` folder. I suspect that after updating the repo using git (maybe because the repo is a submodule?) the `pythonx` folder doesn't get deleted properly necessitating a clean pull. 

2. I found after doing that, I continued to get an error message, but this time similar to #320. I changed line 35 of helpparser.py to read the following

```python
        if sys.platform.startswith('msys') or sys.platform.startswith('win32'):
```

It seems that on Windows, whether I use git bash or cmd, I get the version output from pandoc with the exe line. That is I get `pandoc.exe 2.7.3`,  rather than `pandoc 2.7.3`.

Doing both of these made plugin work for me. Maybe, instead of checking which platform the user is on, the code should always match ".exe" optionally.

**Comment by alerque** [comment]
I think everybody would be happy to have this fixed, but personally I have zero access to Windows for testing these days. I think a PR that better handled Windows issues would be well received as long as it causes no other regressions, but that will probably have to come _from_ somebody(s) who can test on Windows and describe the issue, their approach to fixing it, and test the results.

**Comment by fmoralesc** [comment]
I think @sticke4's proposed solution should work. I have opened a PR with it and some auxiliary changes.
