### ISSUE TITLE
Cannot complete bibliography on Windows 10

### ISSUE THREAD

**Issue by jloow** [vim-pandoc/vim-pandoc#331]
If I try to complete a bibliography entry on Windows 10, I get the following error:

`Fel uppt<e4>cktes vid bearbetning av function pandoc#completion#Complete[12]..pandoc#bibliographies#GetSuggestions[2]..provider#python3#Call:                                                                                                   rad   18:                                                                                                               Error invoking 'python_eval' on channel 3 (python3-script-host):                                                        error caught in request handler 'python_eval ['vim_pandoc.bib.vim_completer.VimCompleter().get_suggestions(vim.eval("a:partkey"))']':                                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\Joel\AppData\Roaming\Python\Python37\site-packages\pynvim\plugin\script_host.py", line 165, in python_eval                                                                                                                         return eval(expr, self.module.__dict__)                                                                               File "<string>", line 1, in <module>                                                                                    File "C:\Users\Joel\AppData\Local\nvim\plugged\vim-pandoc\python3\vim_pandoc\bib\vim_completer.py", line 53, in get_suggestions                                                                                                                   return collator.collate()                                                                                             File "C:\Users\Joel\AppData\Local\nvim\plugged\vim-pandoc\python3\vim_pandoc\bib\fallback.py", line 145, in collate       text = f.read()                                                                                                       File "C:\Users\Joel\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode                   return codecs.charmap_decode(input,self.errors,decoding_table)[0]                                                   UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 343832: character maps to <undefined> `

I don't have these problems on unix.

**Comment by jloow** [comment]
I think I managed to solve the issue by changing line 144 in `fallback.py` to

```python
with open(bib, encoding="utf-8") as f:
```

**Comment by tomhull** [comment]
just to add, I've had this problem for a while and this is identical was my workaround.
I'm using pandoc with a .bib file generated by mendeley, which typically includes some non-ascii characters.

I can provide an example .bib if needed.
