### ISSUE TITLE
Why I `:Pandoc docx` get this error? Thanks!

### ISSUE THREAD

**Issue by Freed-Wu** [vim-pandoc/vim-pandoc#350]
```
|| Error detected while processing function
|| pandoc#command#Pandoc[4]
|| Traceback (most recent call last):
||   File "<string>", line 1, in <module>
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\command.py", line 51, in __call__
||     p = self.pandoc_info.build_argument_parser()
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\helpparser.py", line 124, in build_argument_parser
||     parser.add_argument(*flags, **extra)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1367, in add_argument
||     return self._add_action(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1730, in _add_action
||     self._optionals._add_action(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1571, in _add_action
||     action = super(_ArgumentGroup, self)._add_action(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1381, in _add_action
||     self._check_conflict(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1520, in _check_conflict
||     conflict_handler(action, confl_optionals)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1529, in _handle_conflict_error
||     raise ArgumentError(action, message % conflict_string)
|| argparse.ArgumentError: argument -o/--output: conflicting option string: -o
```

OS: windows10
vim: gvim8.1
python: 3.7
pandoc: 1.13.1

**Comment by mattjbourque** [comment]
I get the same error when I try to compile a markdown file with ":Pandoc html". I am using Gvim 8.2, compiled with python 3 support. ":python3 import sys; print(sys.version)" returns "3.7.5 (default, Oct 27 2019, 15:43:29)"

**Comment by Freed-Wu** [comment]
emmm, i have two computers which are windows and linux. i notice that this error just only occur in windows. are you using windows?

**Comment by mattjbourque** [comment]
No, Debian Linux:
(ins)matt@accordion: ~$ uname -a
Linux accordion 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
>

**Comment by fmoralesc** [comment]
I think this is due to the pandoc version. The way we detect arguments is by parsing the output of `pandoc --help`, so it is not robust to version changes. What pandoc version are you using, @mattjbourque? I am using 2.9.2 in Arch and I can't reproduce the problem.

**Comment by mattjbourque** [comment]
I updated my version of Pandoc. I now have Pandoc 2.5 and that fixes the 
problem. Sorry to waste your time - I ought to have tried that!

**Comment by fmoralesc** [comment]
No worries! The fault is mine, for not coming up with a more robust solution. I hope @Freed-Wu can solve their issue by updating pandoc too... Otherwise we will have to work a little on backwards compatibility.

**Comment by Freed-Wu** [comment]
now i have updated pandoc on my windows computer to the lateset, then i `:Pandoc`, the error has changed:
```
|| Error detected while processing function
|| pandoc#command#PandocComplete[3]
|| Traceback (most recent call last):
||   File "<string>", line 1, in <module>
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\helpparser.py", line 16, in __init__
||     self.update()
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\helpparser.py", line 26, in update
||     self.version = self.get_version()
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\helpparser.py", line 38, in get_version
||     return self.__raw_output('--version', pattern=versionPattern)
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\helpparser.py", line 21, in __raw_output
||     return re.search(pattern, data, re.DOTALL).group(1)
|| AttributeError: 'NoneType' object has no attribute 'group'
```

it is thankful that i use linux computer more frequently than windows and my linux never occur any error on it:)

**Comment by Freed-Wu** [comment]
i have lost my Windows PC. close the issue which cannot be reproduced.
