### ISSUE TITLE
Why I `:Pandoc docx` will get this error? Thanks!

### ISSUE THREAD

**Issue by Freed-Wu** [vim-pandoc/vim-pandoc#351]
```
|| Error detected while processing function
|| pandoc#command#Pandoc[4]
|| Traceback (most recent call last):
||   File "<string>", line 1, in <module>
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\command.py", line 51, in __call__
||     p = self.pandoc_info.build_argument_parser()
||   File "C:/Users/10786/vimfiles/repos/github.com/vim-pandoc/vim-pandoc\python3\vim_pandoc\helpparser.py", line 124, in build_argument_parser
||     parser.add_argument(*flags, **extra)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1367, in add_argument
||     return self._add_action(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1730, in _add_action
||     self._optionals._add_action(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1571, in _add_action
||     action = super(_ArgumentGroup, self)._add_action(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1381, in _add_action
||     self._check_conflict(action)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1520, in _check_conflict
||     conflict_handler(action, confl_optionals)
||   File "D:\Program Files\Python\Python37\lib\argparse.py", line 1529, in _handle_conflict_error
||     raise ArgumentError(action, message % conflict_string)
|| argparse.ArgumentError: argument -o/--output: conflicting option string: -o
```

OS: windows10
vim: gvim8.1
python: 3.7
pandoc: 1.13.1

**Comment by alerque** [comment]
This appears to be a duplicate post of #350.
