### ISSUE TITLE
Error detected while processing function pandoc#command#Pandoc[4]..provider#python3#Call:

### ISSUE THREAD

**Issue by daviewales** [vim-pandoc/vim-pandoc#360]
After updating vim-pandoc today (after not updating for perhaps six months), I encounter the following error, every time I run `:Pandoc`

```
Error detected while processing function pandoc#command#Pandoc[4]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dwales/.vim/vim_plug/vim-pandoc/python3/vim_pandoc/command.py", line 141, in __call__
    self.execute(should_open)
  File "/Users/dwales/.vim/vim_plug/vim-pandoc/python3/vim_pandoc/command.py", line 168, in execute
    vim.command("put='Running pandoc...\n'")
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(put):E115: Missing quote: 'Running pandoc...
```

Pressing 'Enter' at this point yields the following error:

```
Error detected while processing function pandoc#command#JobHandler:
line    7:
E94: No matching buffer for pandoc-execute
```

This also occurs when running `:Pandoc pdf` and `:Pandoc html`.

**Comment by alerque** [comment]
My apologies for the inconvenience @daviewales, I caused this regression by testing a PR is a weird environment that didn't trigger this. It plainly didn't work in the most basic configuration. I think I've fixed that now, if you update again you should be good to go again.

**Comment by daviewales** [comment]
Thanks! It works!
