### ISSUE TITLE
a bibliographies module vim.eval() bug

### ISSUE THREAD

**Issue by qian-lab** [vim-pandoc/vim-pandoc#362]
pandoc completion with omni calling by \<C-x>\<C-o> showed error message:
> Error detected while processing function CompleteR[19]..RmdNonRCompletion[25]..pandoc#completion#Complete[12]..pandoc#bibliographies#GetSuggestions[2]..provider#python3#Call:
line   18:
Error invoking 'python_eval' on channel 3 (python3-script-host):
error caught in request handler 'python_eval ['vim_pandoc.bib.vim_completer.VimCompleter().get_suggestions(vim.eval("a:partkey"))']':
Traceback (most recent call last):
  File "/User/testman/miniconda3/envs/single/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 169, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'vim' is not defined

Here presented a solution to solve this problem caused by vim.eval()

line 37 in vim-pandoc/python3/vim_pandoc/bib/vim_completer.py 
>query = query.strip()

changed to 

> query = vim.eval(query)
query = query.strip()

line 60 in file: vim-pandoc/autoload/pandoc/bibliographies.vim
>let l:sugs = py3eval('vim_pandoc.bib.vim_completer.VimCompleter().get_suggestions(vim.eval("a:partkey"))')

TO:

>let l:sugs = py3eval('vim_pandoc.bib.vim_completer.VimCompleter().get_suggestions("a:partkey")')

**Comment by alerque** [comment]
As I understand it your suggested patch is this:

```patch
--- a/autoload/pandoc/bibliographies.vim
+++ b/autoload/pandoc/bibliographies.vim
@@ -57,7 +57,7 @@ endfunction
 " called by our omnifunc, if completion is enabled
 function! pandoc#bibliographies#GetSuggestions(partkey) abort
     if has('python3')
-        let l:sugs = py3eval('vim_pandoc.bib.vim_completer.VimCompleter().get_suggestions(vim.eval("a:partkey"))')
+        let l:sugs = py3eval('vim_pandoc.bib.vim_completer.VimCompleter().get_suggestions("a:partkey")')
         if len(l:sugs) > 0
             return l:sugs
         else
diff --git a/python3/vim_pandoc/bib/vim_completer.py b/python3/vim_pandoc/bib/vim_completer.py
index e094372..9295533 100644
--- a/python3/vim_pandoc/bib/vim_completer.py
+++ b/python3/vim_pandoc/bib/vim_completer.py
@@ -34,6 +34,7 @@ class VimCompleter(object):
         """
         Returns a dict with the suggestions available for the given query.
         """
+        query = vim.eval(query)
         query = query.strip() # spaces around the query shouldn't be significant
 
         mode = vim.eval("g:pandoc#completion#bib#mode")
```

This doesn't look right to me. `vim.eval()` is used elsewhere in this plugin inside `py3eval()` blocks, so it should be possible here too. That or we have other broken things that never worked.

I'd like to actually know what changed here (or in the vim implementation?) and why shuffling this off to a later scope works (does it even? Or does it just not throw an error because it's never getting invoked?).

**Comment by qian-lab** [comment]
my python veriosn 3.7.6, pynvim 0.4.1
I don't know exactly the problem, may deal with the py3eval function itself, since it calls miniconda3/envs/single/lib/python3.7/site-packages/pynvim/plugin/script_host.py, which is actually "Legacy python/python3-vim emulation".

BTW: the py3eval()  and vim.eval() combination only appear in bibliographies.vim and command.vim, not often invoked?

**Comment by alerque** [comment]
Vim or Neovim? Version?

> BTW: the py3eval() and vim.eval() combination only appear in bibliographies.vim and command.vim, not often invoked?

I noticed that too. It makes me wonder if it's entirely the wrong way to implement that ;-) Also it makes it clear enough our CI testing needs to be fleshed out to cover each thing we expect it to do (but that's a lot of work).

**Comment by qian-lab** [comment]
neovim 0.5.0

**Comment by alerque** [comment]
Neovim 0.5.0 has not been released yet. Unless you are from the future (in which case I have other questions for you) you must be running a nightly build, but there have been 900+ commits worth of changes, and I'm not seeing the same results you are. What is the actual output of `nvim --version`?

**Comment by qian-lab** [comment]
> 
NVIM v0.5.0-10-g0b71bb73e
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-8189da60-4062-4276-8f70-4dcfd64af2d3

Features: +acl +iconv +tui
See ":help feature-compile"
