### ISSUE TITLE
:Pandoc! gives FileNotFoundError error under Windows 10

### ISSUE THREAD

**Issue by Konfekt** [vim-pandoc/vim-pandoc#415]
Running `:Pandoc!` in a buffer of a markdown file `file.md` gives the error message

 ```vim
20210906 15:35:18 vim-pandoc:ran pandoc  --to="html" --output="file.html" "file.md"
Error detected while processing function pandoc#command#PandocAsyncCallback:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\konfekt\vimfiles\plugged\vim-pandoc\python3\vim_pandoc\command.py", line 258, in on_done
    Popen(shlex.split(custom_command))
  File "C:\Python39\Lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\Lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by Konfekt** [comment]
This hinged on my custom `g:pandoc#command#custom_open`.
