### ISSUE TITLE
:Pandoc fails with ValueError (--trace is not in list)

### ISSUE THREAD

**Issue by davidcurie** [vim-pandoc/vim-pandoc#450]
I recently updated pandoc with homebrew and it seems to have broken my vim-pandoc instance.

Things I tried:

- Re-installing vim-pandoc
- Clearing caches in `vim-pandoc/python3/vim_pandoc/__pycache__/`

What works:

- `echo v:version >= 704 && has ("python3")` returns 1
- `pandoc` from the command line works as expected

What doesn't work:

- Running `:Pandoc FORMAT` for any format (html, pdf, etc.) yields the following error:

```python
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/vim/pack/vim-pandoc/start/vim-pandoc/python3/vim_pandoc/command.py", line 294, in <module>
    pandoc = PandocCommand()
             ^^^^^^^^^^^^^^^
  File "/path/to/vim/pack/vim-pandoc/start/vim-pandoc/python3/vim_pandoc/command.py", line 17, in __init__
    self.pandoc_info = PandocInfo(vim.vars["pandoc#command#path"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/vim/pack/vim-pandoc/start/vim-pandoc/python3/vim_pandoc/helpparser.py", line 16, in __init__
    self.update()
  File "/path/to/vim/pack/vim-pandoc/start/vim-pandoc/python3/vim_pandoc/helpparser.py", line 27, in update
    self.options = self.get_options()
                   ^^^^^^^^^^^^^^^^^^
  File "/path/to/vim/pack/vim-pandoc/start/vim-pandoc/python3/vim_pandoc/helpparser.py", line 41, in get_options
    cutoff = data.index('--trace')
             ^^^^^^^^^^^^^^^^^^^^^
ValueError: '--trace' is not in list
```

Specs:

- OSX 12.6.7 (Monterey)
- pandoc 3.1.5
- vim 9.0 (patches 1-1650)
- vim-pandoc (commit d4fc6f8)

**Comment by davidcurie** [comment]
I don't know much about the intent behind the current implementation, but I can fix this issue for myself by editing the appropriate line in `helpparser.py` in a backwards-compatible way:

```diff
-        cutoff = data.index('--trace')
+        try:
+            cutoff = data.index('--trace')
+        except ValueError:
+            cutoff = -1
         data = data[:cutoff]
```

My version of pandoc no longer supplies a `--trace` option under the `pandoc --help` menu.

Happy to submit a Pull Request, or you can internally apply this tweak as a fixup to commit 05f110280326e7a389288f1a88f58f1b5901c6fb
